ALTER TABLE users MODIFY role VARCHAR(16) NOT NULL DEFAULT 'buyer';
UPDATE users SET role = 'vendor' WHERE role = 'seller';
ALTER TABLE users MODIFY role ENUM('buyer', 'vendor', 'admin') NOT NULL DEFAULT 'buyer';

ALTER TABLE orders MODIFY status VARCHAR(32) NOT NULL DEFAULT 'PENDING_PAYMENT';
UPDATE orders SET status = CASE LOWER(status)
  WHEN 'pending_payment' THEN 'PENDING_PAYMENT'
  WHEN 'paid' THEN 'PAID'
  WHEN 'cancelled' THEN 'CANCELLED'
  WHEN 'refunded' THEN 'REFUNDED'
  ELSE status
END;
ALTER TABLE orders MODIFY status ENUM('PENDING_PAYMENT', 'PAID', 'CANCELLED', 'REFUNDED') NOT NULL DEFAULT 'PENDING_PAYMENT';

ALTER TABLE reports MODIFY status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
UPDATE reports SET status = UPPER(status);
ALTER TABLE reports MODIFY status ENUM('PENDING', 'REVIEWED', 'RESOLVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
